apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.6.0-rc1/manifests/install.yaml

images:
  - name: quay.io/argoproj/argocd
    newName: acrswcvessyinc.azurecr.io/argoproj/argocd
    newTag: v3.6.0-rc1