apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:full-admin, *, *, *, allow
    g, "26c170fc-3976-46be-95a7-dff9e9533455", role:full-admin
