apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
       url: https://argocd.vessyinc.com/
       oidc.config: |
             name: Azure
             issuer: https://login.microsoftonline.com/9cdec346-9087-4758-a5a5-2144a3ed72d4/v2.0
             clientID: 6ae1669e-737d-4846-85a8-f73aa9764958
             requestedIDTokenClaims:
                groups:
                   essential: true
             requestedScopes:
                - openid
                - profile
                - email